-keep class com.google.mlkit.** { *; }
-keep class com.google.firebase.** { *; }
-keep class com.google.android.gms.** { *; }
-keep class com.google.** { *; }
-keep class androidx.** { *; }
-keep class com.facebook.** { *; }
-keep class com.app.meedu.** { *; }